steps:
  # Step 1: Build the container
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/ghostbusters-api:$COMMIT_SHA', '.']
    dir: '/workspace/src/ghostbusters_api'

  # Step 2: Push the container
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/ghostbusters-api:$COMMIT_SHA']

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'ghostbusters-api-container'
      - '--image=gcr.io/$PROJECT_ID/ghostbusters-api:$COMMIT_SHA'
      - '--platform=managed'
      - '--region=us-central1'
      - '--project=$PROJECT_ID'
      - '--allow-unauthenticated'
      - '--memory=2Gi'
      - '--cpu=2'
      - '--concurrency=80'
      - '--max-instances=10'
      - '--timeout=900'
      - '--set-env-vars=PROJECT_ID=$PROJECT_ID'
      - '--service-account=1077539189076-compute@developer.gserviceaccount.com'

images:
  - 'gcr.io/$PROJECT_ID/ghostbusters-api:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: '100' 