# .pre-commit-config.yaml
# Practical pre-commit configuration that allows common test patterns and logging

repos:
  # Black (Code formatting)
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        args: [--line-length=88]

  # Ruff (Fast Python linter) - with practical exclusions
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.6
    hooks:
      - id: ruff
        args: [--fix, --ignore=S101,G004,N806,PTH123,DTZ005,DTZ003,DTZ007,S607,S604,S105,S324,S306,S104,B904,ARG001,ARG002,F811,F821,F403,F405,N999,SLF001,EXE005,E402,E722,S112,SIM102,SIM105,SIM117,COM818]
        # S101: assert statements (common in tests)
        # G004: f-string logging (acceptable for logging)
        # N806: variable names in functions (test-specific)
        # PTH123: open() vs Path.open() (minor preference)
        # DTZ005/DTZ003/DTZ007: datetime timezone issues (minor)
        # S607/S604: security issues (handled separately)
        # S105/S324/S306: security issues (handled separately)
        # S104: binding to all interfaces (development)
        # B904: exception chaining (minor)
        # ARG001/ARG002: unused arguments (test-specific)
        # F811/F821/F403/F405: import issues (test-specific)
        # N999: module names (generated files)
        # SLF001: private member access (test-specific)
        # EXE005: shebang placement (test-specific)
        # E402: import order (test-specific)
        # E722: bare except (test-specific)
        # S112: try-except-continue (acceptable)
        # SIM102/SIM105/SIM117: simplification (minor)
        # COM818: trailing commas (minor)
      - id: ruff-format
