#!/usr/bin/env python3
"""
Round-Trip Model System Generated Code

This package contains code generated by the round-trip model system,
demonstrating the complete cycle: Design → Model → Code → Model
"""

from .proven_ASTAnalyzer import ASTAnalyzer
from .proven_QualityOrchestrator import QualityOrchestrator
from .proven_QualityRule import QualityRule

__all__ = ["QualityRule", "ASTAnalyzer", "QualityOrchestrator"]

__version__ = "1.0.0"
__author__ = "Model-Driven System"
__description__ = "Generated code from round-trip model system"
